Add action for exporting SignupTarget participants to CSV
City-of-Helsinki/open-city-signups pull request #10
Opened 2018-05-23 07:23 UTC by igordavydsson

Closes #9

2018-05-23 07:59 UTC, tuomas777 requested changes

2018-05-23 07:59 UTC, tuomas777 commented on signups/admin.py
> +            return self.message_user(request, _(u"Valitse vain yksi Signup Target"), messages.ERROR)
Source language for translated fields should be English.

2018-05-23 07:59 UTC, tuomas777 commented on signups/admin.py
> +        participants = signup_target.users.all()
This should exclude cancelled sign-ups, ie. `signup_target.users.exclude('cancelled_at'=None))`

2018-05-23 07:59 UTC, tuomas777 commented on signups/admin.py
> +        response['Content-Disposition'] = 'attachment; filename=orders.csv'
Not sure why the field is named `orders` :) Also, maybe include signup target name and some kind of rough timestamp to the filename as well?

2018-05-23 07:59 UTC, tuomas777 commented on signups/admin.py
> +    export_participants.short_description = _("Vie osallistujen lista CSV-tiedostoon")
Should be `osallistujien`. Actually maybe "Lataa ilmoittautuneiden lista CSV-tiedostona." would be better.

2018-05-23 09:01 UTC, igordavydsson commented
@tuomas777 good points! fixed things up.

2018-05-24 11:02 UTC, tuomas777 approved these changes
👍

2018-05-24 11:03 UTC, merged